### DISCUSSION TITLE
Using robotidy on CI

### DISCUSSION THREAD

**Discussion by higor-haider** [MarketSquare/robotframework-tidy#675] [Q&A] [answered]
Hello all,

I want to configure robotidy to be executed on a gitlab-ci pipeline, how can I do that?

**Comment by bhirsz** [comment]
I would start by defining what is you goal. Do you want Robotidy to run with the same configuration you are using locally and warn if the file was modified in CI? And it would work as test if file was or wasnt formatted properly ie in PR.

In that case you want to keep configuration i file (to make it easier to reuse the same configuration) and run Robotidy with additional command '--check' (https://robotidy.readthedocs.io/en/stable/quickstart.html#status-code). It will run the tool, not modify files but return status 1 if any file was modified.

Gitlab should fail any build with the command that returns 1 status code. As per configuring build you can reuse build for any python tool. I can find and share example if needed later

**Reply by higor-haider** [reply]
Yes, that's exactly what I need. An example will come in handy.

**Reply by bhirsz** [reply, marked as answer]
Example pipeline:

```
stages:
  - formatting
 
robotidy:
  stage: formatting
  image: python:3.12
  before_script:
    - pip install robotframework-tidy
  script:
    - robotidy --check .
  only:
    - merge_requests

```

I didn't test it - if it works, mention it here so I can add it to our documentation as example.

And Robotidy by default looks for configuration file in the project root, that's why we don't need to provide path to config file. "pip install robotframework-tidy" will also install most recent robotframework version (if nothing was installed before). If you wish to use specific version of robot framework then specify the version:

```
pip install robotframework==6.1.1 robotframework-tidy
```
