### DISCUSSION TITLE
robotframework-tidy as a gitlab pipeline check

### DISCUSSION THREAD

**Discussion by piyushasaran12** [MarketSquare/robotframework-tidy#721] [Q&A] [answered]
I need to include robotframework-tidy as a gitlab pipeline check can anyone help how to do this? Also, if a separate config file is needed can someone give example?

**Comment by bhirsz** [comment]
The same config file you are using when running locally will be enough (and even better since you want to use the same settings to avoid differences). You only need the tool to return non-0 exit code so the pipeline will fail:

https://robotidy.readthedocs.io/en/stable/quickstart.html#status-code

If you run robotidy with ``--check`` it will no overwrite the files, but only check and return 0 or 1 depending if files would be modified. You can additionally pass ``--diff`` flag if you also want to log possible modifications in the pipeline output.

**Reply by piyushasaran12** [reply]
when trying it locally I just ran it manually by using this command  robotidy /path/to/tests no separate config file was created. Now I wish to include this as a precheck in our pipeline, it would be nice if some examples can be given for the script.

**Reply by bhirsz** [reply, marked as answer]
If you didn't use any extra config, you also don't need anything extra besides ``--check`` in the pipeline. 

First you need to ensure you have robotidy installed in Gitlab runner. That depends on your work environment, but either add it to docker that is build and used for your runner or simply install it in the pipeline directly. I don't know your setup, but for example:

```
stages:
  - gitlab used those stages, you can add your own stage here
  - Code Quality
  - E2E Tests (and other stages you already have)

code_quality:
  stage: Code Quality
  image:
    name: ""docker image used to run your linters etc, or whatever you use in your company CI"
  script:
    - pip install robotframework-tidy  # if you didn't install it in the docker already
    - robotidy --check /path/to/tests
```
