### ISSUE TITLE
AlignKeywordsSection: Fatal exception occurred in SplitTooLongLine

### ISSUE THREAD

**Issue by m-n-a-g** [MarketSquare/robotframework-tidy#659]
Robotidy AlignKeywordsSection fails with 

```sh
pre-commit\repo_v65_hrp\py_env-python3.9\lib\site-packages\robotidy\transformers\SplitTooLongLine.py", line 351, in <genexpr>
    return sum(len(token.value) for token in tokens)
AttributeError: 'NoneType' object has no attribute 'value'
Fatal exception occurred. You can create an issue at https://github.com/MarketSquare/robotframework-tidy/issues . Thanks!
```

due to 

```robot
*** Settings ***
Documentation       Bug: Fatal exception occurred in SplitTooLongLine.py

Library             BuiltIn


*** Keywords ***
Reproduce Fatal exception bug in SplitTooLongLine
    [Documentation]    This fails because of the missing `...` in the multiline argument
    [Arguments]    ${Multiline_Argument1}    ${Multiline_Argument2}    ${Multiline_Argument3}    ${Multiline_Argument4}
                    ${Multiline_Argument5}    ${Multiline_Argument6}    ${Multiline_Argument7}    ${Multiline_Argument8}
    ...    ${Multiline_Argument9}    ${Multiline_Argument10}    ${Multiline_Argument11}    ${Multiline_Argument12}
    ...    ${Multiline_Argument13}    ${Multiline_Argument14}    ${Multiline_Argument15}    ${Multiline_Argument16}

    Should Be Equal     ${Multiline_Argument1}    ${Multiline_Argument2}
```

pyproject.toml:
```toml
[tool.robotidy]
diff = false
overwrite = true
verbose = false
separator = "space"
spacecount = 4
line_length = 120
lineseparator = "native"
skip_gitignore = false
ignore_git_dir = false
configure = ["AlignKeywordsSection:enabled=True:alignment_type=auto:handle_too_long=compact_overflow"]
```

Python 3.9.9
RobotFramework-Tidy: 4.10.0
