### ISSUE TITLE
Importing transformer 'GenerateDocumentation' failed. Verify if correct name or configuration was provided.

### ISSUE THREAD

**Issue by mikeleppane** [MarketSquare/robotframework-tidy#715]
Hey! I'm getting the following error when trying to run `robotidy`:
```bash
Error: Importing transformer 'GenerateDocumentation' failed. Verify if correct name or configuration was provided.
```

Versions:
```bash
robotidy, version 4.14.0

Robot Framework 7.0.1 (Python 3.11.6 on win32)
```
This has worked before, but I don't know why this now happens.

**Comment by bhirsz** [comment]
Do you use it with any specific config? GenerateDocumentation uses jinja so it could be also because of change in the depending library - I would need to check.

The error itself doesn't tell much, I will look into possiblity of printing whole error stack if used with --verbose flag (in the future).

**Comment by mikeleppane** [comment]
Yes we have some pre-defined config:
```toml
[tool.robotidy]
overwrite = true
skip-tags = true
spacecount = 4
configure = [
    "NormalizeTags:enabled=False",
]
```
