### ISSUE TITLE
"MergeAndOrderSections:create_comment_section=False" does remove existing comments

### ISSUE THREAD

**Issue by violette** [MarketSquare/robotframework-tidy#738]
Hi,

I tried to use with precommit hooks:
```
    - repo: https://github.com/MarketSquare/robotframework-tidy
      rev: 4.16.0
      hooks:
          - id: robotidy
            types: [file]
            files: \.robot$
            args: ["--configure", "MergeAndOrderSections:create_comment_section=False"]
```
but if I test with existing comments like in your example on https://robotidy.readthedocs.io/en/stable/transformers/MergeAndOrderSections.html,
```
*** Comments ***
I am a comment
```
it removes the `*** Comments ***` lines except if placed at the beginning of the file.

IMO, the `*** Comments ***`  should not be removed if existing previously in the file.
